"""create db

Revision ID: 64be0c7a3e41
Revises: 
Create Date: 2024-06-02 23:54:39.520941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64be0c7a3e41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('username', sa.String(length=100), nullable=False),
                    sa.Column('email', sa.String(length=100), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )

    op.create_table('post',
                    sa.Column('title', sa.String(length=100), nullable=False),
                    sa.Column('author', sa.String(length=100), nullable=False),
                    sa.Column('body', sa.String(length=100), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'])
                    )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('post')
    # ### end Alembic commands ###
