version: "3"

services:

  pg:
    image: postgres
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d blog -U user" ]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    environment:
      DATABASE_URI: "postgresql+psycopg://user:example@pg:5432/blog"
#    command:
#      - flask
#      - run
    ports:
      - "8000:8000"
#    entrypoint:
#      - bash
#      - "entrypoint.sh"
#    network_mode: host
    depends_on:
      pg:
        condition: service_healthy

volumes:
  db-data: